name: Build
on:
  push:

jobs:
  build:
    name: Build
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore vcpkg cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: vcpkg-

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: e5a1490e1409d175932ef6014519e9ae149ddb7c

      - name: Integrate vcpkg
        run: vcpkg integrate install

      - name: Build app for release
        run: msbuild obs-updater.slnx -property:Configuration=${{ matrix.configuration }}

      - uses: actions/upload-artifact@v4
        with:
          name: updater-x64-${{ matrix.configuration }}
          path: x64/${{ matrix.configuration }}

      - name: Save vcpkg cache
        uses: actions/cache/save@v4
        # The cache is the same for release and debug, but only save it on Release runs
        if: matrix.configuration == 'Release'
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ hashFiles('vcpkg.json') }}
